gcp_seed_secrets:
  billing_id: ENC[AES256_GCM,data:uqWmPw6uee0BOTKNrMaheW6DnuY=,iv:x3TNWjAcLWaUER+yQAh7R25ibQD4G8zy/BG8CXb916Q=,tag:KHg1dhdGatJyz74xjdrPAA==,type:str]
  sa_name: ENC[AES256_GCM,data:Ogrm/gFYemmXx/J42A==,iv:P9x9SzYbT94TBCpurkSd4uEmfG89FbaSsDvSjlq4kws=,tag:1WlFebSwV9EXF9RErbI6aA==,type:str]
  developers:
    - name: ENC[AES256_GCM,data:JkFzRxwdNHyedA==,iv:KmmJw4LJjqIqobjP8DAqwO2N6y98Bb/YXoE+rqE0O2Y=,tag:1j+nwKb3YyWcFKuQngWI2g==,type:str]
      email: ENC[AES256_GCM,data:sZ58FqZJA03qfl3SSZrw21riqUBkIgST1Tw=,iv:EpTJ7gvHkqc8I8TsVAwDcbxHvyC2TckMEgtSxVAlQ1g=,tag:yQfIMVlc6ZykCGDYQ4C6kw==,type:str]
      role: ENC[AES256_GCM,data:AW19BNc=,iv:mK/SrM+zG27/V9hjIiWDKvnSvTwiEg8TYpU8JyNAnew=,tag:1BEJUw1biTvigKJqSxV2JA==,type:str]
sops:
  lastmodified: "2026-05-20T22:53:04Z"
  mac: ENC[AES256_GCM,data:XE5hhqTJNpr8y7Y3C82g7eteyjl/3bvDL0wcRwGPiJ8Xwb2UL3HiisciF0ExU5gLby09v7gqd1QhrQ/ufMyQ9+k+n2+uEA+vE2ZO4yOozYiKn0Dx7Lnnkc2Wa+aqKxJWezlMGlZoyVCf2KXv+5HpOjQmRyfCD8qVjWW9uz8PWCA=,iv:+UC9NCOZ6B+/pm208Ulsxh3xZons/SBu+5EKRHOmvT4=,tag:8Eh0bVcRIV9/ZkJDpE7oew==,type:str]
  pgp:
    - created_at: "2026-05-20T22:53:04Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv/dLLSWFSsIM0MB9o7w3gNmB19evhn3cItstASz+kahdTF
        I4SEyjgKmfzdXl55PN98X2obRFkV4L2AkFVgPTs4c2fhV+axvoMCp0sQjfQMdZS+
        HYCQqBlBJfF8wKh/Lu0fel49TWXfh4uKt3NdpoOOjjBV05p8QLUdvn7OZsQ+yu88
        9BZl0xvLpB7faDvpWi8M587be3ynsiTrPskc8T10Ar/7onefDgdYsNTzCpRNlekD
        pJpxeRTKdYF82ukEMW/icZxRBsPvjAq42lTICQEYLyAXUOmEoCkBRGKHb2F4F72p
        IOxB/jaUMD3XxE68vDOFhsmUiBxyVn1PpWvn9kTkkXixcpLhphjljS/NVf3Hf9Ie
        iu2R1KxU++meUwuIgMak4CiSwtCqVgJRZKHPR4jCZXsOaC8XvbM60ovFzeasKyTn
        DZWIP7glepHFgZTE8bBg2kGnxUrf7VjsfdctTS2ns7d9YDd13Etzcg93zxAB1uZ6
        c3hZoIWRYtWuCH7NVfqT0l4BgTIELQ2nUIKJ+Mhj+NNdjUDw2vFtFHDAWLheZfco
        4RGM/BKtFidRW6r+Drx+8DCK2nqh33rAPsOETT3dFSnodyog5fUlZ/dBOV2GMffu
        6VeDDySK6vstsRfSLxQ0
        =Y9sX
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-05-20T22:53:04Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlAQ//XB49/UtIwmXBcgjFJIdtaQNADYhgCL+B6Pt/WfBwjVYj
        lCwS2w73wwBVLyHHV8GFHINbnUvBFhbg56Or9QrEZeSFblNHPrk/siHncibb4xEv
        cFsjRPK8k5+vKRMWtMurRWHqUfWYymSfhpqZfrpzVoqnq2VovbvtuHgTgIO8NIPH
        hvhPwW7Y1zLdQoYAXPTMCWVEtxS2UHnRo4n9cOvxZ05Yo9lhqqMV5TYatTGcuwcC
        8fDlzHVraHe/JpS4E6SNcWlN727UVxHzJiwGTt8rdF7RHf/GNV+p5ZzebFl2zPYO
        EKrbD+FjUz9rQDr3Sv+04cYlVIyUFwfbQYNbXHYZ99Zq/EuydI5Wn+rBSf3DfPNg
        QEm0yXb8Mb0Ggnxdp/2+52Pg04o6/qPri6eBuwaGvSte8gIPft+nEbzlnYYb7n21
        k9f5bl+QU5yz7Bu1DoouPtvi4MtR9VkLnduEk6taQ88YILtLEiJ0dpDvwApbVonW
        1skkIqpyN42vHKoF/V0FXZdobgSwYZQg8jxP7h1nOY+EAqjHOO0A5USFQ+D768Yg
        d2I+LvFCGQ2QpHrE999paatLXwnyEyAxf5FF09UMjpDxt0dn8oM8UJkLqvS7uj4S
        8r7107lX8dZ1ramg7rCCvZGGVN/NU5rn1Fcq3VbUKFreAHxcrLSGWnU8/ca9C2jS
        XgHzG57BLtRJvDuMcnmr9jDyivYZgrYOQZgZo/GHCt2b1WwVAzDoS6BUiZaCGvMJ
        b0vAN0rdG9pF4NwOKfao2LazvhY8/Fbi5F2H1eV0b3Hs/gOksD/ZT/EdfBM1Ftw=
        =L5cH
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
